sally_node:
  ros__parameters:
    # Motor ids & offsets
    steer_ids: [1, 2, 3, 4]
    drive_ids: [5, 6, 7, 8]
    lift_ids: [9, 10]
    steer_offsets: [0.0, -20.0, 45.0, -45.0]
    lift_offsets: [-0.0, 0.0]
    lift_lowered: 200.0
    lift_zero: 0.0
    lift_raised: -464.0
    # Robot parameters
    mass: 8.3
    magnet_force: 50.0
    radius: 0.025
    height: 0.064
    width: 0.317
    length: 0.433
    friction: 0.9
    max_torque: 2.0
    # Controller parameters
    regularization: 1.0e-3
    kp: 70.0
    kd: 10.0
    

